const Strings = {
    AppName: "Reo Coin Wallet",
    intro1: 'Happiness is a journey, enjoy exploring it!',
    intro1desc: 'Happiness is a state of emotion that most of us aspire to but are unsure about how to get there.',
    intro2: 'Get surrounded with positive people!',
    intro2desc: 'Positivity acts like a shield against negativity. It forgives, heals, encourages and inspires.',
    intro3: 'Count your blessings and invest in Love!',
    intro3desc: 'This helps to frame a better attitude and takes off of the negativies.',
    intro4: 'Focus on the present!',
    intro4desc: "Right now is the only moment guaranteed to us. Right now, is life. Don't miss it.",
    letsBegin: "LET'S BEGIN",
    skip: "SKIP",
    login: 'Login',
    enterEmail: 'Enter Email Address',
    otpDesc: 'We will send you an OTP (One Time Password) on this email address.',
    getOtp: 'GET OTP',
    verification: 'Verification',
    otpSent: 'OTP sent to ',
    enterOtp: 'Enter OTP',
    expire: 'Expire in : 1:20',
    verify: 'VERIFY AND PROCEED',
    home: 'Home',
    habitBuilder: 'Habit Builder',
    stories: 'Stories',
    profile: 'Profile',
    happyOMeter: 'Happy-O-Meter',
    benchmarkScore: 'Benchmark Score',
    support: 'Support',


    //drawer
    explore: 'Explore Happiness Track',
    wowLife: 'Wow Life',
    exports: 'Experts',
    inspirationalStories: 'Inpirational Stories',
    resources: 'Resources',
    poll: "Poll",
    dailyCalender: "Daily Calender",
    contact: 'Contact',
    help: "Help",
    logout: "Logout",
    howAreYouFeel: "How are you feeling right now?",
    joyful: 'joyful',
    lonely: 'lonely',
    motivated: 'motivated',
    sad: 'sad',
    angry: 'angry',
    relaxed: 'relaxed',
    seeAll: 'SEE ALL',
    books: 'Books',
    happynessScore: 'My Happiness Score',


}

export default Strings